import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import './styles/globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Sankofa+Display&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
